# Site settings
title: Diksha
description: 'I am Diksha, currently pursuing my Bachelors in Technology in Computer Science from Indira Gandhi Delhi Technical University for Women. I love to code and learn new technologies. DJango, Website Development and Algorithms fascinate me. I am a core team member of CodeBenders- programming club and CodeChef campus chapter of my college. I like to encourage girls to code.'
url: 'https://diksha-rathi.github.io/'
baseurl: 'https://diksha-rathi.github.io/'
google_analytics: 'UA-74332052-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Diksha'
  email: diksha.2895@gmail.com
  github_username:  diksha-rathi
  linkedin_username:  diksharathi
  codechef_username:  codegirl1995
  twitter_username: diksha_28795
  #facebook_username: username

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
