# Site settings
title: Diksha
description: 'Hi, I am Diksha, pursuing my major in Computer Science. I received the prestigious Google Anita Borg Scholarship in 2016. I love to code and learn new technologies. Django, Website Development and Algorithms fascinate me. I am involved in various initiatives to encourage girls to code. When I am not coding, I write, craft DIYs, paint, and capture the world and emotions around. I also have a keen interest in the Indian History and enjoy public speaking.'
url: 'http://diksha-rathi.github.io'
baseurl: ''
google_analytics: 'UA-74332052-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Diksha'
  email: diksha.2895@gmail.com
  github_username:  diksha-rathi
  linkedin_username:  diksharathi
  pinterest_username: diksha2895
  twitter_username: diksha_28795
  #facebook_username: username

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
