# Site settings
title: Diksha
description: 'Hi, I am Diksha, currently exploring my developer instincts at Microsoft. I am one of the 50 recipients from Asia- Pacific of the Google Anita Borg Scholarship- 2016. I am involved with initiatives to encourage women in STEM. When I am not around my laptop, I love to spend my time running/ cycling on the roads of Hyderabad.'
url: 'http://diksha-rathi.github.io'
baseurl: ''
google_analytics: 'UA-74332052-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Diksha'
  email: diksha.2895@gmail.com
  github_username:  diksha-rathi
  linkedin_username:  diksharathi
  pinterest_username: diksha2895
  twitter_username: diksha_28795
  #facebook_username: username

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
